### ISSUE TITLE
Want to add LeetCode Q.771 (Java Solution)

### ISSUE THREAD

**Issue by aditya-517** [JATINAGGARWAL123/Hacktober#15]
Hey @JATINAGGARWAL123 ,
I want to add LeetCode Easy Q771 Jewels & Stones Java Solution.
Can you please assign this issue to me & add HacktoberFest label.

**Comment by Harsh-COE** [comment]
yes i do

**Comment by Bhavya1912** [comment]
@JATINAGGARWAL123 sir can you assign me an issue for hacktoberfest 🙏
