### ISSUE TITLE
Adding a question with solution from codeforces

### ISSUE THREAD

**Issue by Rohan1412** [JATINAGGARWAL123/Hacktober#9]
problem
https://codeforces.com/contest/1520/problem/B

**Comment by Rohan1412** [comment]
Please assign me under hacktober fest label

**Comment by JATINAGGARWAL123** [comment]
I assigned , you can start your work

**Comment by sgaurav37533** [comment]
Can i work on another problem from @JATINAGGARWAL123 Please assign me the same issue with some another problem so i can participate in hacktoberfest
